### ISSUE TITLE
Running task (BodyCompositionTask) twice causes segmentation fault

### ISSUE THREAD

**Issue by rbrecheisen** [rbrecheisen/MosamaticDesktop#2]
Steps to reproduce:

- Run MuscleFatSegmentationTask
- Run BodyCompositionTask
- Run BodyCompositionTask again (same or different settings)

Error message:

Traceback (most recent call last):
  File "/Users/Ralph/dev/tools/RapidExplorer/src/app/widgets/taskdockwidget.py", line 90, in runSelectedTask
    self._taskManager.runCurrentTask(background=True)
  File "/Users/Ralph/dev/tools/RapidExplorer/src/app/tasks/taskmanager2.py", line 52, in runCurrentTask
    QThreadPool.globalInstance().start(self._currentTask)
RuntimeError: Internal C++ object (BodyCompositionTask) already deleted

Possible cause:

QThreadPool is trying to run the current task. Perhaps that reference is lost somehow and we need to explicitly set the current task again based on the currently selected task in the combobox?

**Comment by rbrecheisen** [comment]
For some reason running the task in the background (using QThreadPool) caused the task to be deleted after it was finished. The Python object in the task manager's dictionary, however, was still there. Since a task only needs to be alive while running, we can create them easily on the fly. So, the task manager just loads the task types (classes) and instantiates them only at the last moment. So, every repeat run of a task (type) results in a new task object. This solves the problem.
